

# 이 ci 코드는 깃허브에서 검증을 할때 잠깐 리눅스 가상 컴퓨터를 한대 빌려서 밑에 있는 검증 사항들을 싹다 해주는 코드라고 보면 됩니다

name: 'Terraform CI'

on:
  push:
    branches: [ "main" ] # main 브랜치에 코드가 올라올 때 실행 하는거 ci 를 하는 이유
  pull_request:
    branches: [ "main" ] # main으로 합쳐달라는 요청이 올 때 실행

jobs:
  terraform-check:
    name: 'Terraform Lint and Validate'
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 코드 가져오기
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 테라폼 설치
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0 # 프젝 할때 똑같은 버전을 써야 오류가 없습돠

      # 3. 테라폼 초기화
      - name: Terraform Init
        run: terraform init -backend=false

      # 4. 테라폼 포맷 검사
      - name: Terraform Format
        run: terraform fmt -check

      # 5. 테라폼 문법 및 논리 검사 ㅇㅇ
      - name: Terraform Validate
        run: terraform validate

       # 6. 테라폼 플랜 (실제 리소스 변경 사항 확인) => 일부러 넣었습니다
      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        continue-on-error: true # 플랜이 실패해도 CI 전체가 중단되지  않게 함 (에러 확인용)
